apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
  namespace: default
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
